# Generated by Django 4.2.3 on 2024-05-28 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Defines Username', max_length=20)),
                ('user_email', models.EmailField(help_text='Defines Email', max_length=254)),
                ('user_password', models.CharField(help_text='Defines User Password - Encrypted and verified', max_length=60)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='TempURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(help_text='Verification Code to verify the user', max_length=32)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Defines Username', max_length=20)),
                ('user_email', models.EmailField(help_text='Defines Email', max_length=254)),
                ('user_password', models.CharField(help_text='Defines User Password - Encrypted and verified', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TempVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(help_text='Login verification Code', max_length=6)),
                ('username', models.CharField(max_length=20)),
                ('user_try_count', models.IntegerField(default=3)),
            ],
        ),
    ]
