# Generated by Django 4.2.3 on 2024-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Defines Username', max_length=20)),
                ('user_email', models.EmailField(help_text='Defines Email', max_length=254)),
                ('user_password', models.CharField(help_text='Defines User Password - Encrypted and verified', max_length=60)),
            ],
        ),
    ]
